### ISSUE TITLE
Pipes 4.1.4 fails to compile

### ISSUE THREAD

**Issue by idontgetoutmuch** [Gabriel439/Haskell-Pipes-Library#132]
src/Pipes.hs:86:8:
    Could not find module ‘Control.Monad.Morph’
    Perhaps you haven't installed the profiling libraries for package ‘mmorph-1.0.4’?
    Use -v to see a list of the files searched for.
Failed to install pipes-4.1.4

**Comment by idontgetoutmuch** [comment]
Some cabal weirdness caused by some libraries being built with profiling and some without. I haven't been able to figure out why pipes tried to build with profiling. Building in a sandbox worked. It shall forever remain one of life's great unsolved mysteries.

**Comment by Gabriel439** [comment]
Can you still reproduce the error outside of the sandbox?

**Comment by Gabriel439** [comment]
I'll go ahead and mark this closed as I think this is probably specific to your BUILD environment.  However, if you still have issues you can reopen this.
