### ISSUE TITLE
Add change log

### ISSUE THREAD

**Issue by treeowl** [Gabriel439/Haskell-Pipes-Library#134]
The title says it all.

**Comment by Gabriel439** [comment]
I've been keeping track of the change log here:

https://github.com/Gabriel439/Haskell-Pipes-Library/releases

However, I'm guessing you mean that you want this as part of the cabal description for the package, right?

**Comment by treeowl** [comment]
Yes, doing so will put it up on Hackage where everyone will be able to find
it. If you already have the log, it should be trivial to set that up
properly.

**Comment by ocharles** [comment]
:+1: I just saw a new release is out, and it's not evident what the changes are - I went straight to the Hackage page, where no changelog is linked.
