### ISSUE TITLE
Consider adding toListM' :: Monad m => Producer a m r -> m ([a], r)

### ISSUE THREAD

**Issue by danidiaz** [Gabriel439/Haskell-Pipes-Library#136]
It would be nice to have a "toListM" variant that preserved the return value of the Producer, thus ensuring that it has been exhausted.

It could be used to define analogous variants  of "toLazyM" in pipes-bytestring and pipes-text.

My motivation is that some functions in "process-streaming" can work faster when they are sure they are exhausting the producer.

**Comment by Gabriel439** [comment]
Yeah, I think is fine as long it has the same warning as `toList`.  Would you be able to write up a pull request for this?

**Comment by Gabriel439** [comment]
I'm closing this since we resolved the issue in the related pull request.
