### ISSUE TITLE
Some useful additions

### ISSUE THREAD

**Issue by FranklinChen** [Gabriel439/Haskell-Pipes-Library#148]
I started using Pipes and love it. I suggest some useful additions that I needed to write up for my own use. I'm curious about why the focus on returning () when one might as well return something useful. In my case, I'm using Pipes to do computations that return something at the end, while reporting on progress.

```haskell
stdoutLn' :: MonadIO m => Consumer' String m r
toListM' :: Monad m => Producer a m r -> m ([a], r)
```

**Comment by Gabriel439** [comment]
I'm definitely in favor of adding both.  Could you submit a pull request to add these?

**Comment by Gabriel439** [comment]
Never mind!  I found time to do this myself.  Thanks for the suggestion!

**Comment by FranklinChen** [comment]
Gack, I was going to get around to this, thanks! :-)

**Comment by Gabriel439** [comment]
You're welcome! :)
