### ISSUE TITLE
Frames leak memory

### ISSUE THREAD

**Issue by Shimuuar** [Gabriel439/Haskell-Pipes-Library#15]
Here is minimal test case. Memory consumption steadily increases. Note that NOINLINE pragma is crucial. Without it enumerateGZFileList gets inlined and leak disappear

```
module Main(main) where
import Control.Frame
import Control.IMonad

enumerateGZFileList :: [FilePath] -> Frame () IO (M ()) C ()
enumerateGZFileList nms
  = close !> mapMR_ (const $ foreverR $ yield ()) nms
{-# NOINLINE enumerateGZFileList #-}

takeF :: Monad m => Int -> Frame a m (M a) C ()
takeF 0 = close
takeF n = await !>= yield !> takeF (n - 1)

main :: IO ()
main = 
  runFrame
    $   foreverR await
    <-< takeF 100000
    <-< enumerateGZFileList ["A"]
```

**Comment by zoranbosnjak** [comment]
This problem is suppose to be fixed in GHC long time ago, but it stil (again) leaks memory when using `forever`. Is this a new problem or reintroduction of the same problem? 

This is the testcase (tested with ghc version is 8.6.5):

```haskell
-- test1.hs
-- ghc -O2 -Wall test1.hs && ./test1

import Control.Monad
import Pipes

main :: IO ()
main = runEffect (source >-> sink) where 
    source = forever (yield ())
    sink = forever (await >> return ())

    -- this version (without 'forever') has no leak
    --source = yield () >> source
    --sink = await >> sink
```

**Comment by Gabriel439** [comment]
@zoranbosnjak: I cannot reproduce, using `ghc-8.6.4` and `pipes-4.3.9`, compiled with `-O2`

**Comment by zoranbosnjak** [comment]
@Gabriel439: I will try with the same versions.
What is your method to determine if it leaks memory or not?
How much time do you observe a running program?

**Comment by Gabriel439** [comment]
@zoranbosnjak: I tested both informally (by observing memory after running for a minute) and also more formally by collecting a heap profile, like this:

```bash
$ ghc -prof -rtsopts -O2 test.hs
$ ./test +RTS -h
<Ctrl-C after some duration>
$ hp2ps -c test.hp
```

... which shows that the program runs in constant space

**Comment by zoranbosnjak** [comment]
@Gabriel439 : I could not reproduce the problem using `ghc-8.6.4` and `pipes-4.3.9`. However, a test program in combination with `ghc-8.6.5` and `pipes-4.3.11` leaks.

I have tested some other combinations. Please check `pipes`, commit
896a7e3: Relax Monad constraints to Functor (#194)
It seems like this is where it started to appear. It's after the `pipes-4.3.9`.

**Comment by Gabriel439** [comment]
@zoranbosnjak: Thanks!  That gives me enough to go on to fix this
