### ISSUE TITLE
Pipes.Tutorial Beginning List Is Misformatted

### ISSUE THREAD

**Issue by CarlEdman** [Gabriel439/Haskell-Pipes-Library#153]
The list of [Effects, Streaming, Composability] at the beginning of the Pipes.Tutorial text is malformatted which may slightly confuse readers.

![malformat](https://cloud.githubusercontent.com/assets/705407/10265386/0bba90a2-69fc-11e5-9272-4c8642fbe2a9.png)

**Comment by Gabriel439** [comment]
Fixed!

Apparently this was an issue with the `haddock` tool distributed using `ghc-7.8`.  Now the list is formatted correctly on Hackage

**Comment by CarlEdman** [comment]
Thanks!

**Comment by Gabriel439** [comment]
You're welcome!
