### ISSUE TITLE
Relax Monad constraint to Functor

### ISSUE THREAD

**Issue by infinity0** [Gabriel439/Haskell-Pipes-Library#165]
The default way of recursing a Proxy transformation `f` inside the M case is to do `M m -> M m >>= \p' -> return (f p')` which can be simplified to `M (fmap f m)`, in many cases allowing us to relax the Monad constraint to Functor.

I made a start to this in infinity0/Haskell-Pipes-Library@5218df7d but do you think it's a good idea? If so I can complete it and send in a PR. I don't see a specific use case for a non-Monad Functor Pipe right this minute, but someone else might in the future.

**Comment by Gabriel439** [comment]
I do eventually plan on doing this.  I was just waiting until Debian stable upgrades to `ghc-7.10.3` so that there are no noisy `(Functor m, Monad m)` constraints in the code

**Comment by infinity0** [comment]
Because of how the release process works, Debian stable is highly unlikely to get 7.10.3 until (probably) 2017-05 when stretch (current Debian testing) will probably be released as stable. However 7.10.3 is already in [jessie-backports](https://packages.debian.org/jessie-backports/ghc) - which stable users would need to manually add to their system. Not sure if this changes your plans.

**Comment by Gabriel439** [comment]
I'm fine waiting.  There's no hurry

**Comment by tswilkinson** [comment]
I presume that using `fmap f` rather than `>>= return . f` would also make `pipes` at least slightly faster?

**Comment by siddhanathan** [comment]
> I presume that using fmap f rather than >>= return . f would also make pipes at least slightly faster?

A lot faster, I would assume. build/foldr fusion should be a lot nicer.

**Comment by cronokirby** [comment]
Is there still interest in working on this?

**Comment by Gabriel439** [comment]
@cronokirby: Yep!  This is fixed now.  Thanks 🙂
