### ISSUE TITLE
pipes tutorial link is broken

### ISSUE THREAD

**Issue by huseyinyilmaz** [Gabriel439/Haskell-Pipes-Library#187]
Well, this is not a good place to report this probably, but I could not find a better place to do it. So I will just leave this here:

* I searched for "haskell pipes tutorial" on google
* First result was "https://hackage.haskell.org/package/pipes/docs/Pipes-Tutorial.htm" and I clicked it.
* Page redirected to following page "https://hackage.haskell.org/package/pipes-4.3.1/docs/Pipes-Tutorial.html" which returns a 404.

**Comment by Gabriel439** [comment]
Oops!  For some reason the package upload didn't upload the documentation correctly but I just re-uploaded the documentation and the link should work now

Thank you for reporting this! :)

**Comment by huseyinyilmaz** [comment]
Yes, it is working now. Thanks for the quick fix.

**Comment by Gabriel439** [comment]
You're welcome!
