### ISSUE TITLE
Fix ListT MMonad instance

### ISSUE THREAD

**Issue by ivan-timokhin** [Gabriel439/Haskell-Pipes-Library#188]
Current instance (e3fc775) is
```haskell
instance MMonad ListT where
    embed f m = Select (enumerate (embed f m))
```
…which is just an infinite loop, unless I'm completely misunderstanding something.

For a simple demonstration,
```haskell
runEffect $ for (enumerate $ pure False) (lift . print)
```
prints `False`, whereas
```haskell
runEffect $ for (enumerate $ embed lift $ pure False) (lift . print)
```
loops indefinitely, even though `embed lift` should be equal to `id` by `MMonad` laws.

**Comment by Gabriel439** [comment]
I verified that both examples succeed and produced the same result after this fix.  The fix is up on Hackage as `pipes-4.3.2`

**Comment by ivan-timokhin** [comment]
Thanks!

**Comment by Gabriel439** [comment]
You're welcome!
