### ISSUE TITLE
Stream Concat  with Pipes ?

### ISSUE THREAD

**Issue by nhenin** [Gabriel439/Haskell-Pipes-Library#211]
Hi, I need to concat a stream on each value produced by an processing upstream... Basically appending a `Producer` to a `Pipe`, I'm struggling a bit doing that with Pipes... 

Thanks !

**Comment by Gabriel439** [comment]
You can convert a `Producer` to a `Pipe` of the same output type, like this:

```haskell
import Pipes
import Pipes.Core

producerToPipe :: Monad m => Producer b m r -> Pipe a b m r
producerToPipe producer = closed >\\ producer
```

... and then once you do so you can sequence the `Producer` after any `Pipe` that shares the same output type:

```haskell
producerAfterPipe :: Monad m => Pipe a b m r -> Producer b m r -> Pipe a b m r
producerAfterPipe pipe producer = do
    pipe
    producerToPipe producer
```

**Comment by nhenin** [comment]
Thanks !!

**Comment by Gabriel439** [comment]
@nhenin: You're welcome! 🙂
