### ISSUE TITLE
Explanation of the name "Proxy"

### ISSUE THREAD

**Issue by chris-martin** [Gabriel439/Haskell-Pipes-Library#216]
This is mostly just a question, but possibly a documentation issue: Why "Proxy"? I don't think I see the connection between the word and what it is, which is making me feel like there may be a larger concept or useful metaphor that I'm missing out on.

**Comment by Gabriel439** [comment]
@chris-martin: All of the bidirectional machinery uses terms from networking (e.g. `Client`/`Server`/`Proxy`), so the name `Proxy` is meant to evoke what is known in networking as a "reverse proxy".  In other words, a service that you directly make requests to which then translates those to new requests that it makes on your behalf.

**Comment by chris-martin** [comment]
Ah yes, when I look at just the names `Client`, `Server`, and `Proxy`, I see they form a coherent system. Much-belated thank you for clarifying.

**Comment by Gabriel439** [comment]
You're welcome! 🙂
