### ISSUE TITLE
toHandle should not insert a newline automatically

### ISSUE THREAD

**Issue by andrewufrank** [Gabriel439/Haskell-Pipes-Library#219]
Today I was caught by the silent insertion of newline using `toHandle`. I found the previous discussion which suggested to rename `toHandle`  to `hPutStrLn`. I would be happy with a `toHandle` and a `toHandleLn`. 

I found by painful experience that functions should do only one thing and not for convenience add other functions. The additional functionality is typically causing enormous cost in those cases where the "convenience" is not wanted; usually searching for the explanation of an error. IMHO `toHandle` should just write to the handle whatever is there without adding anything.

Thank you for Pipe! It is an excellent demonstration of how powerful Haskell is.

**Comment by Gabriel439** [comment]
@andrewufrank: The main reason that `toHandle` is line-based is for symmetry with `fromHandle` (which is also line-based)

What about adding two new utilities named `putHandle` and `putHandleLn` with a note in teh documentation that `toHandle` is a synonym for `putHandleLn`?

**Comment by andrewufrank** [comment]
good solution - thank you! I will wait to see it in the next release. (I tried to make a putHandle myself, but it did not work; likely I was distracted by the application issue I wanted to solve. )
